### ISSUE TITLE
issues while trying to do the training

### ISSUE THREAD

**Issue by jorgeramirez** [magic282/NeuSum#21]
Hi, I finally got to the point where I can do the training. After I run the script "run.sh" the training process starts fine but after a few minutes it hangs and I ran out of memory (15gb ram and one Tesla K80 GPU). I am not sure what is the problem, what I can see on the log file is the following:

```txt
2019-05-26 15:19:23,975 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (204798)
2019-05-26 15:19:23,981 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (204805)
2019-05-26 15:19:24,155 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (204956)
2019-05-26 15:19:24,212 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (205017)
2019-05-26 15:19:24,259 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (205070)
2019-05-26 15:19:24,297 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (205117)
2019-05-26 15:19:24,327 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (205150)
2019-05-26 15:19:24,545 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (205357)
2019-05-26 15:19:24,602 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (205383)
2019-05-26 15:19:24,835 [INFO :onlinePreprocess] WARNING: oracle exceeds max_doc_len, ignoring (205522)
```

This is my modified run.sh script

```bash
NEUSUM_HOME=$PWD

export CUDA_VISIBLE_DEVICES=0

cd $NEUSUM_HOME/code/NeuSum/neusum_pt

python train.py -save_path $NEUSUM_HOME/data/models/neusum \
                -online_process_data \
                -max_doc_len 80 \
                -train_oracle $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/train.oracle.txt \
                -train_src $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/train.src.txt \
                -train_src_rouge $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/train.regain.txt \
                -src_vocab $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/vocabulary.txt \
                -train_tgt $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/train.tgt.txt \
                -tgt_vocab $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/vocabulary.txt \
                -layers 1 -word_vec_size 50 -sent_enc_size 256 -doc_enc_size 256 -dec_rnn_size 256 \
                -sent_brnn -doc_brnn \
                -dec_init simple \
                -att_vec_size 256 \
                -norm_lambda 20 \
                -sent_dropout 0.3 -doc_dropout 0.2 -dec_dropout 0\
                -batch_size 64 -beam_size 1 \
                -epochs 100 \
                -optim adam -learning_rate 0.001 -halve_lr_bad_count 100000 \
                -gpus 0 \
                -curriculum 0 -extra_shuffle \
                -start_eval_batch 1000 -eval_per_batch 1000 \
                -log_interval 100 -log_home $NEUSUM_HOME/data/models/neusum \
                -seed 12345 -cuda_seed 12345 \
                -pre_word_vecs_enc $NEUSUM_HOME/data/glove/glove.6B.50d.txt \
                -freeze_word_vecs_enc \
                -dev_input_src $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/val.4k.src.txt \
                -dev_ref $NEUSUM_HOME/data/cnndm/finished_files/chunked_txt/val.4k.tgt.txt \
                -max_decode_step 3 -force_max_len
```

Any ideas?

**Comment by jorgeramirez** [comment]
Added more memory and my problem is currently this one:

```
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/home/jorge/auto-highlighting/src/neusum/code/NeuSum/neusum_pt/neusum/xinit.py", line 217, in xavier_normal
    if isinstance(tensor, Variable):
RecursionError: maximum recursion depth exceeded
```

**Comment by magic282** [comment]
Please follow the README to use PyTorch v0.3.x

**Comment by magic282** [comment]
Or change the parameter initialization part in train.py

**Comment by jorgeramirez** [comment]
whoops! 
btw you docker image did the trick, thanks!
